### Santé de l'API QCM
GET http://localhost:3001/health

### Créer un QCM
POST http://localhost:3001/qcms
Content-Type: application/json
X-User-Id: 1

{
  "title": "QCM Géographie Europe",
  "questions": [
    {
      "text": "Quelle est la capitale de la Norvège ?",
      "choices": ["Stockholm", "Oslo", "Copenhague", "Helsinki"],
      "correctChoiceIndex": 1
    },
    {
      "text": "En quelle année la Pologne est-elle entrée dans l'Union européenne ?",
      "choices": ["1999", "2001", "2004", "2007"],
      "correctChoiceIndex": 2
    },
    {
      "text": "Quelle est la capitale de la Hongrie ?",
      "choices": ["Prague", "Varsovie", "Budapest", "Vienne"],
      "correctChoiceIndex": 2
    },
    {
      "text": "Quel pays a pour capitale Reykjavik ?",
      "choices": ["Lichtenstein", "Islande", "Moldavie", "Estonie"],
      "correctChoiceIndex": 1
    }
  ]
}

### Lister les QCMs
GET http://localhost:3001/qcms